apiVersion: v1
description: Kubernetes Auditor by AppsCode
name: auditor
version: v2021.08.22
appVersion: v0.0.1
home: https://github.com/kubeops/auditor
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/auditor
maintainers:
- name: appscode
  email: support@appscode.com
