apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falco-ui-server.fullname" . }}
  labels:
    {{- include "falco-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - falco.appscode.com
  resources:
  - "*"
  verbs: ["*"]
# Get cluster id
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs: ["get", "list", "watch"]
