{{- if eq .Values.enable "templates" -}}
{{- range $path, $content :=  .Files.Glob "library/**/**.yaml" -}}
{{- $obj := toString $content | fromYaml -}}
{{- $kind := dig "kind" "" $obj -}}
{{- if eq $kind "ConstraintTemplate" -}}
# {{ $path }}
{{ toString $content }}
---
{{ end -}}
{{- end -}}
{{- end -}}