apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - auditor.appscode.com
  - core.k8s.appscode.com
  - identity.k8s.appscode.com
  - meta.k8s.appscode.com
  - ui.k8s.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  # create used for raw REST query
  - create
  - get
  - list
  - watch
- nonResourceURLs:
  - '*'
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
