apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - auditor.appscode.com
  - identity.k8s.appscode.com
  - ui.k8s.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
