apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: appscode
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://charts.appscode.com/stable/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bytebuilders
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://bundles.byte.builders/stable/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bytebuilders-ui
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://bundles.byte.builders/ui/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
spec:
  interval: 30m
  url: https://nats-io.github.io/k8s/helm/charts/
